services:
  gh_stats:
    container_name: gh_stats
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - nginx
    command: npm run start
    restart: always

networks:
  nginx:
    external: true
    name: nginx
